import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Noise from "@/components/Noise";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
	title: "Next Playground",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang='en'>
			<body className={"min-w-full flex justify-center m-auto items-center relative antialiased"}>
				{children}
				<Noise />
			</body>
		</html>
	);
}
